<?php get_header(); $hero=ma_theme_hero_post(); ?>
<div class="wrap home-grid">
  <aside class="service-column"><div class="service-stack"><details open><summary>Veranstaltungen</summary><div class="service-body"><?php $events=function_exists('ma_upcoming_events')?ma_upcoming_events(6):[]; if($events): foreach($events as $e): $ts=function_exists('ma_event_timestamp')?ma_event_timestamp($e->ID):0; ?><a class="event-mini" href="<?php echo esc_url(get_permalink($e)); ?>"><span class="event-date"><?php echo $ts?esc_html(wp_date('d M',$ts)):'Termin'; ?></span><span><strong><?php echo esc_html(get_the_title($e)); ?></strong><br><?php echo $ts?esc_html(wp_date('H:i',$ts).' Uhr · '):''; ?><?php echo esc_html((string)get_post_meta($e->ID,'ma_event_place',true)); ?></span></a><?php endforeach; ?><a class="read-more" href="<?php echo esc_url(get_post_type_archive_link('ma_event')); ?>">Alle Veranstaltungen</a><?php else: ?><p class="empty">Aktuell keine freigegebenen Termine.</p><?php endif; ?></div></details>
  <?php $w=function_exists('ma_get_weather')?ma_get_weather():null;if($w): ?><details><summary>Wetter</summary><div class="service-body"><?php foreach($w['days'] as $i=>$d): ?><div class="weather-day"><span><strong><?php echo $i===0?'Heute':($i===1?'Morgen':'Übermorgen'); ?></strong><br><?php echo esc_html($d['icon'].' '.$d['label']); ?></span><span><?php echo esc_html($d['max'].'° / '.$d['min'].'°'); ?><br><?php echo esc_html($d['rain'].' % Regen'); ?></span></div><?php endforeach; if(!empty($w['stale'])):?><p class="empty">Letzter gültiger Stand: <?php echo esc_html(wp_date('H:i',strtotime($w['updated_at']))); ?> Uhr</p><?php endif; ?></div></details><?php endif; ?>
  <?php foreach(['ma_property'=>'Immobilien','ma_job'=>'Stellen','ma_obituary'=>'Traueranzeigen','ma_family_notice'=>'Familienanzeigen'] as $pt=>$label): ?><details><summary><?php echo esc_html($label); ?></summary><div class="service-body"><?php $items=function_exists('ma_active_market_items')?ma_active_market_items($pt,3):[]; if($items): foreach($items as $item): ?><p><a href="<?php echo esc_url(get_permalink($item)); ?>"><strong><?php echo esc_html(get_the_title($item)); ?></strong></a></p><?php endforeach; else: ?><p class="empty">Aktuell keine Anzeigen.</p><?php endif; ?></div></details><?php endforeach; ?></div></aside>
  <section class="main-feed"><?php if($hero): setup_postdata($GLOBALS['post']=$hero); ?><article class="hero"><?php if(has_post_thumbnail()) the_post_thumbnail('full'); ?><div class="eyebrow"><?php echo ma_theme_location_label(); ?> · <?php $c=get_the_category(); echo esc_html($c[0]->name??'Aktuell'); ?></div><h1><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h1><?php if(has_excerpt()): ?><p class="dek"><?php echo esc_html(get_the_excerpt()); ?></p><?php endif; ?><div class="meta-line"><span><?php echo esc_html(get_the_date('d.m.Y · H:i')); ?> Uhr</span><span><?php echo ma_theme_reading_time(); ?> Min. Lesezeit</span><a href="<?php the_permalink(); ?>#comments"><?php echo (int)get_comments_number(); ?> Kommentare</a></div><a class="read-more" href="<?php the_permalink(); ?>">Mehr lesen</a></article><?php wp_reset_postdata(); endif; ?>
    <div class="news-list"><?php $exclude=$hero?[$hero->ID]:[];$q=new WP_Query(['post_type'=>'post','post_status'=>'publish','posts_per_page'=>10,'post__not_in'=>$exclude]);$i=0;while($q->have_posts()):$q->the_post();get_template_part('template-parts/card');$i++;if($i===4) ma_theme_ad('homepage_feed_1');endwhile;wp_reset_postdata(); ?></div>
  </section>
  <aside class="home-aside"><div class="sidebar-heading">Lokale Anzeigen</div><?php ma_theme_ad('homepage_sidebar_top'); ma_theme_ad('homepage_sidebar_middle'); ?><div class="sidebar-heading">Sport</div><?php echo do_shortcode('[ma_sport]'); ?></aside>
</div><?php get_footer(); ?>
